[package]
name = "atombutter"
authors = ["Denis Benato <benato.denis96@gmail.com>"]
version = "0.3.1"
edition = "2021"

[dependencies]
libc = { version = "^0.2", features = [] }

[profile.release]
strip = "debuginfo"
lto = "thin"
panic = "unwind"

[package.metadata.deb]
license-file = ["LICENSE.md", "4"]
extended-description = """\
An init program to mount rootfs before transferring process to \
systemd or any other deamon."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/atombutter", "usr/bin/", "755"],
]
