[package]
name = "atombutter"
authors = ["Denis Benato <benato.denis96@gmail.com>"]
version = "0.1.3"
edition = "2021"

[dependencies]
libc = { version = "^0.2", features = [] }
sys-mount = { version = "^3.0", features = [] }

[package.metadata.deb]
license-file = ["LICENSE.md", "4"]
extended-description = """\
A command-line utility to login into a user accounts: \
supports either greetd and pam."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/atombutter", "usr/bin/", "755"],
]
